apiVersion: v1
kind: Service

metadata:
  name: ms-timeline
  labels:
    app: ms-timeline
    tier: backend

spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: ms-timeline
    tier: backend
